In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np

In [15]:
(Xtr,ytr),(Xts,yts)=mnist.load_data()
Xtr=Xtr/255
Xts=Xts/255

In [16]:
print(ytr[:10])

[5 0 4 1 9 2 1 3 1 4]


In [17]:
ytr=to_categorical(ytr,10)
yts=to_categorical(yts,10)


In [18]:
print(ytr[:10])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [19]:
model=Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128,activation="relu"),
    Dense(64,activation="relu"),
    Dense(10,activation="softmax")
]
)


In [20]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])


In [21]:
model.fit(Xtr,ytr,epochs=5,batch_size=32,validation_data=(Xts,yts),verbose=1)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - accuracy: 0.9304 - loss: 0.2359 - val_accuracy: 0.9549 - val_loss: 0.1390
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9705 - loss: 0.0972 - val_accuracy: 0.9669 - val_loss: 0.0990
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.9790 - loss: 0.0675 - val_accuracy: 0.9721 - val_loss: 0.0933
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.9833 - loss: 0.0531 - val_accuracy: 0.9759 - val_loss: 0.0797
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9868 - loss: 0.0407 - val_accuracy: 0.9748 - val_loss: 0.0799


In [22]:
model.save("digit_recogniser.h5")