In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report

iris=load_iris()
X=iris.data
y=iris.target
print(X.shape,y.shape)

(150, 4) (150,)


In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#cm+cr
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)


cr = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(cr)

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [9]:
from sklearn.preprocessing import OneHotEncoder
ohc=OneHotEncoder(sparse_output=False)
y=y.reshape(-1,1)
encoded_y=ohc.fit_transform(y)
print(encoded_y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [10]:
nn_Xtrain,nn_Xtest,nn_ytrain,nn_ytest=train_test_split(X,encoded_y,test_size=0.2,random_state=42)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
nn=Sequential([
    Dense(16,activation="relu",input_shape=(4,)),
    Dense(16,activation="relu"),
    Dense(3,activation="softmax")
])
nn.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
nn.fit(nn_Xtrain,nn_ytrain,epochs=20,batch_size=5,validation_split=0.1,verbose=1)

Epoch 1/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.4722 - loss: 1.0495 - val_accuracy: 1.0000 - val_loss: 0.8843
Epoch 2/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.8259 - val_accuracy: 0.5833 - val_loss: 0.7923
Epoch 3/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7685 - loss: 0.7333 - val_accuracy: 0.9167 - val_loss: 0.7262
Epoch 4/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9074 - loss: 0.6614 - val_accuracy: 0.9167 - val_loss: 0.6699
Epoch 5/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7222 - loss: 0.6023 - val_accuracy: 0.8333 - val_loss: 0.6298
Epoch 6/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8704 - loss: 0.5548 - val_accuracy: 0.9167 - val_loss: 0.5910
Epoch 7/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9074 - loss: 0.5160 - val_accuracy: 1.0000 - val_loss: 0.5550
Epoch 8/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8611 - loss: 0.4816 - val_accuracy: 0.9167 - v

In [15]:
loss,accuracy=nn.evaluate(nn_Xtest,nn_ytest)
print(loss)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.9667 - loss: 0.2626
0.2625786364078522
0.9666666388511658


In [16]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print(score)

1.0
